spring.application.name=oodo_backend
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/odoobackend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=Satyendra@1234
spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.output.ansi.enabled=ALWAYS